### ISSUE TITLE
Status is being cut out from the version before.

### ISSUE THREAD

**Issue by NeXiDE** [vulxdev/Vulx#31]
Currently: ![image](https://user-images.githubusercontent.com/66691455/193470476-4e9d0d76-778d-45a7-a2c8-7f9cd8c28522.png)

Version before: ![image](https://user-images.githubusercontent.com/66691455/193470500-ef458bd7-f86b-415e-bbae-28a94bfbf947.png)

Is this intentionally or on purpose?

**Comment by AquaPlaysYT** [comment]
Yes this was intentional, it stops things like this being possible however patreon will receive a new status editor that makes this safer soon

**Comment by NeXiDE** [comment]
Alrighty ^^
