### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by xODYSSEYx** [vulxdev/Vulx#46]
when i open vulx is just continuously says refreshing entitlements so i cant use it, how do i fix this.

**Comment by Sneepex2** [comment]
same here

**Comment by BloodyToolzz** [comment]
Everyone has this problem I think.

**Comment by BloodyToolzz** [comment]
> when i open vulx is just continuously says refreshing entitlements so i cant use it, how do i fix this.

You'll have to wait about 10 seconds after launching Valorant, then launch Vulx and it most likely should work.
