### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by maplepy** [vulxdev/Vulx#48]
> Vulx is a profile editor made for Valorant that creates a dedicated dashboard allowing for full customisation within the clients presence service. Built using Node.JS and requiring zero authentication Vulx offers the best features while prioritizing the users experience smile

That does not explain what it does at all?

**Comment by SiLeNSwOrD** [comment]
It allows you to change your rank, level and status that is visible to players on your friends list

**Comment by maplepy** [comment]
so like a hack?

**Comment by SiLeNSwOrD** [comment]
> so like a hack?

Far from a hack.

**Comment by maplepy** [comment]
>  change your rank, level 

> Far from a hack.

how so?

**Comment by iam4pple** [comment]
It’s all server-side, Vulx sends the custom information to the Valorant API and then it shows up on your profile.

**Comment by maplepy** [comment]
So it modifies the level,rang etc. on the server permanently is that right?
